export const routes = {
  index: "/",
  home: {
    index: "/home",
  },
  menu: {
    index: "/menu",
    starters: "/menu/starters",
    kids: "/menu/kids",
    mainDish: "/menu/main-dish",
    drinks: "/menu/drinks",
    loungeDrinks: "/menu/drinks/lounge",
    fingers: "/menu/starters/fingers",
    soups: "/menu/starters/soups",
    springRoll: "/menu/starters/spring-roll",
    asian: "/menu/main-dish/asian",
    desserts: "/menu/main-dish/desserts",
    pasta: "/menu/main-dish/pasta",
    rice: "/menu/main-dish/rice",
    salads: "/menu/main-dish/salads",
    seaFoods: "/menu/main-dish/sea-foods",
    steaks: "/menu/main-dish/steaks",
    burger: "/menu/kids/burger",
    kidsMain: "/menu/kids/main",
    sides: "/menu/kids/sides",
    restaurant: "/menu/restaurant",
    lounge: "/menu/lounge",
    flaming: "/menu/lounge/flaming",
    royal: "/menu/lounge/royal",
    loungeSides: "/menu/lounge/sides",
    loungeSoups: "/menu/lounge/soups",
    special: "/menu/lounge/special",
  },
  reservation: {
    index: "/reservation",
  },
  contact: {
    index: "/contact",
  },
};
