export const foodMenu = [
  {
    id: 1,
    name: "Atlantic Prawn Bisque",
    description:
      "Silken prawn bisque, delicately infused with herbs, served with crisp artisan croutons",
    price: "₦12,666.79",
    category: "Soups",
  },
  {
    id: 2,
    name: "Classic Chicken Pepper Consommé",
    description:
      "Traditional spiced chicken pepper soup, accompanied by freshly baked buns",
    price: "₦15,668",
    category: "Soups",
  },
  {
    id: 3,
    name: "Classic Goat Pepper Pot",
    description: "Slow-simmered goat meat pepper soup with tender yam cubes",
    price: "₦12,093.80",
    category: "Soups",
  },
  {
    id: 4,
    name: "Classic Catfish Pepper Consommé",
    description: "Aromatic catfish pepper soup, served with soft warm buns",
    price: "₦10,559.57",
    category: "Soups",
  },
  {
    id: 5,
    name: "Char-Grilled Chicken Tikka Masala",
    description:
      "Tender chicken in aromatic masala sauce, served with buttered naan bread",
    price: "₦9,740",
    category: "Soups",
  },
  {
    id: 6,
    name: "Smoked Goat Asun & Caramelized Plantain",
    description:
      "Char-grilled goat meat finished with peppers, onions, and ripe plantain",
    price: "₦9,050.20",
    category: "Fingers",
  },
  {
    id: 7,
    name: "Buffalo-Glazed Chicken Wings",
    description:
      "Crispy wings tossed in buffalo glaze, served with roasted garlic aioli",
    price: "₦7,232.40",
    category: "Fingers",
  },
  {
    id: 8,
    name: "Chicken in London",
    description: "Golden-fried chicken bites with a delicate seasoned crust",
    price: "₦6,560.03",
    category: "Fingers",
  },
  {
    id: 9,
    name: "Golden Beer-Battered Onion Rings",
    description: "Served with a honey mustard dipping sauce",
    price: "₦3,445.60",
    category: "Fingers",
  },
  {
    id: 10,
    name: "Classic Atlantic Prawn Cocktail",
    description:
      "Chilled prawns with crisp lettuce and signature cocktail dressing",
    price: "₦13,478.0",
    category: "Fingers",
  },
  {
    id: 11,
    name: "Golden Chicken Taquitos",
    description:
      "Rolled tortillas filled with seasoned chicken, served with a zesty house dip",
    price: "₦3,340.2",
    category: "Fingers",
  },
  {
    id: 12,
    name: "Sticky Glazed Lamb Ribs",
    description: "Slow-roasted lamb ribs finished in a rich, glossy glaze",
    price: "₦10,735",
    category: "Fingers",
  },
  {
    id: 13,
    name: "Shrimps in Mayo Spring Rolls",
    description: "Golden pastries filled with savory Shrimps and mayo sauce",
    price: "₦2,730",
    category: "Spring Roll",
  },
  {
    id: 14,
    name: "Chicken spring roll",
    description: "Golden pastries filled with Spiced chicken",
    price: "₦2,250",
    category: "Spring Roll",
  },
  {
    id: 15,
    name: "Vegetarian spring roll",
    description: "Golden pastries filled with savory vegetables and spices ",
    price: "₦2,000",
    category: "Spring Roll",
  },
  {
    id: 16,
    name: "Beef spring roll",
    description: "Golden pastries filled with umami flavored beef",
    price: "₦2,250",
    category: "Spring Roll",
  },
];

export const desertMenu = [
  {
    id: 1,
    name: "Braise de Jarret d’Agneau",
    description: "Slow-braised lamb shank served with velvety mashed potatoes",
    price: "₦35,668",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 2,
    name: "Jay’s Golden Hammer",
    description:
      "Signature Thor’s Hammer cut, expertly roasted and served with herb potato wedges",
    price: "₦70,689",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 3,
    name: "Teriyaki-Glazed Ribeye Steak",
    description: "Char-grilled ribeye served with vibrant chimichurri sauce",
    price: "₦28,875",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 4,
    name: "Ribeye Steak with Fresh Chimichurri",
    description: "Char-grilled ribeye served with vibrant chimichurri sauce",
    price: "₦28,875",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 5,
    name: "Bone-In Prime Steak",
    description: "Finished with a luxurious red wine jus",
    price: "₦32,200",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 6,
    name: "Cowboy Tomahawk Steak",
    description: "An impressive long-bone steak, flame-grilled to perfection",
    price: "₦38,625",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 7,
    name: "Linguine alla Bolognese Classico",
    description: "Traditional slow-cooked meat ragu with fine herbs",
    price: "₦23,547",
    category: "Pasta Selection",
  },
  {
    id: 8,
    name: "Penne all’Arrabbiata",
    description: "Al dente penne in a bold tomato and chili sauce",
    price: "₦17,679.90",
    category: "Pasta Selection",
  },
  {
    id: 9,
    name: "Fettuccine Alfredo with Grilled Chicken",
    description: "Creamy parmesan sauce finished with tender chicken",
    price: "₦24,962",
    category: "Pasta Selection",
  },
  {
    id: 10,
    name: "Four-Cheese Maccheroni Indulgence",
    description:
      "A rich, creamy, baked macaroni and cheese dish featuring a blend of four distinct cheeses to create layers of flavor and a luxurious texture",
    price: "₦18,983.90",
    category: "Pasta Selection",
  },
  {
    id: 11,
    name: "Wok-Tossed Teriyaki Chicken Noodles",
    description: "Silky noodles with glazed chicken and vegetables",
    price: "₦15,667.79",
    category: "Asian Inspiration",
  },
  {
    id: 12,
    name: "Traditional Shoyu Ramen",
    description: "Classic Japanese noodle soup with soy-based broth",
    price: "₦13,652",
    category: "Asian Inspiration",
  },
  {
    id: 13,
    name: "Coconut-Infused Seafood Rice",
    description:
      "Fragrant rice delicately cooked with seafood and coconut essence",
    price: "₦23,683",
    category: "Rice and Signature Specialties",
  },
  {
    id: 14,
    name: "Mediterranean Greek Seafood Rice",
    description: "Rice infused with herbs, olive oil, and fresh seafood",
    price: "₦24,287.50",
    category: "Rice and Signature Specialties",
  },
  {
    id: 15,
    name: "Surf & Turf Prawn & Chicken Rice",
    description: "A refined combination of succulent prawns and tender chicken",
    price: "₦19,887.50",
    category: "Rice and Signature Specialties",
  },
  {
    id: 16,
    name: "Sizzling Beef Stir-Fry",
    description: "Premium beef strips wok-seared with seasonal vegetables",
    price: "₦15,657",
    category: "Rice and Signature Specialties",
  },
  {
    id: 17,
    name: "Golden Pineapple Fried Rice",
    description: "Aromatic rice tossed with pineapple and spices",
    price: "₦13,362.50",
    category: "Rice and Signature Specialties",
  },
  {
    id: 18,
    name: "Offada Reloaded – Chef’s Interpretation",
    description:
      "Traditional Nigerian Ofada rice elevated with rich accompaniments",
    price: "₦18,992.80",
    category: "Rice and Signature Specialties",
  },
  {
    id: 19,
    name: "Jay’s Signature Basmati Rice",
    description:
      "Perfectly steamed flavored and spiced long-grain basmati rice infused with Gizzard and glazed plantain.",
    price: "₦14,998.90",
    category: "Rice and Signature Specialties",
  },
  {
    id: 20,
    name: "The Grand Seafood Boil (serves 2)",
    description: "A luxurious assortment of seafood, infused with house spices",
    price: "₦57,667",
    category: "Seafood Delicacies",
  },
  {
    id: 21,
    name: "Blood Orange–Glazed Atlantic Salmon",
    description: "Pan-seared salmon finished with citrus reduction",
    price: "₦20,674",
    category: "Seafood Delicacies",
  },
  {
    id: 22,
    name: "Creamy Lemon & Dill Salmon",
    description: "Salmon in a delicate cream sauce infused with fresh dill",
    price: "₦22,235",
    category: "Seafood Delicacies",
  },
  {
    id: 23,
    name: "“Marry Me” Signature Salmon",
    description: "Chef’s celebrated salmon in a rich, velvety sauce",
    price: "₦24,186",
    category: "Seafood Delicacies",
  },
  {
    id: 24,
    name: "Cajun-Spiced Tiger Prawns",
    description: "Succulent prawns finished with bold Cajun seasoning",
    price: "₦22,359.37",
    category: "Seafood Delicacies",
  },
  {
    id: 25,
    name: "Cajun-Spiced Tiger Prawns",
    description: "Succulent prawns finished with bold Cajun seasoning",
    price: "₦22,359.37",
    category: "Seafood Delicacies",
  },
  {
    id: 26,
    name: "Ocean’s Harvest Platter",
    description: "An exquisite selection of premium seafood",
    price: "₦38,270",
    category: "Seafood Delicacies",
  },
  {
    id: 27,
    name: "Flames of the Sea",
    description: "Chef’s flambéed seafood showcase",
    price: "₦47,359",
    category: "Seafood Delicacies",
  },
  {
    id: 28,
    name: "Classic Caesar Salad",
    description: "Crisp romaine, parmesan shavings, and house dressing",
    price: "₦15,750",
    category: "Salads",
  },
  {
    id: 29,
    name: "Chilled Shrimp Garden Salad",
    description: "Fresh greens topped with tender shrimp",
    price: "₦12,650",
    category: "Salads",
  },
  {
    id: 30,
    name: "Creamy Classic Coleslaw",
    description: "Finely shredded cabbage in a delicate dressing",
    price: "₦9,137.50",
    category: "Salads",
  },
  {
    id: 31,
    name: "Mediterranean Pasta Salad",
    description: "Pasta tossed with herbs, vegetables, and olive oil",
    price: "₦10,276.05",
    category: "Salads",
  },
  {
    id: 32,
    name: "Golden Orchard Fruit Tart",
    description: "Seasonal fruits on a buttery pastry base",
    price: "₦9,670",
    category: "Dessert",
  },
  {
    id: 33,
    name: "Vanilla double Panna Cotta",
    description: "Silky Italian dessert with subtle vanilla notes",
    price: "₦9,060",
    category: "Dessert",
  },
  {
    id: 34,
    name: "Decadent Chocolate Indulgence Cake",
    description: "Rich chocolate layers with smooth ganache",
    price: "₦10,137",
    category: "Dessert",
  },
  {
    id: 35,
    name: "Classic Cinnamon-Spiced Apple Pie",
    description: "Warm apple filling encased in golden past",
    price: "₦12,367",
    category: "Dessert",
  },
];

export const kidsMenu = [
  {
    id: 1,
    name: "Chicken & Chips",
    description:
      "Crispy chicken tenders with golden French fries, served with ketchup",
    price: "₦7,000",
    category: "Main Dishes",
  },
  {
    id: 2,
    name: "Cheesy Mac & Cheese",
    description: "Creamy elbow pasta baked with three kinds of melty cheese",
    price: "₦9,000",
    category: "Main Dishes",
  },
  {
    id: 3,
    name: "Sticky Chicken Wings",
    description: "Sweet and tangy glazed wings that are finger-licking good",
    price: "₦8,950",
    category: "Main Dishes",
  },
  {
    id: 4,
    name: "Jollof Rice & Grilled Chicken",
    description: "Flavorful tomato rice with tender grilled chicken drumstick",
    price: "₦10,500",
    category: "Main Dishes",
  },
  {
    id: 5,
    name: "Chicken Buffalo Burger",
    description:
      "Juicy chicken patty with mild buffalo sauce and crispy lettuce",
    price: "₦12,790",
    category: "Burgers",
  },
  {
    id: 6,
    name: "Chicken Parmesan Burger",
    description:
      "Breaded chicken patty topped with marinara sauce and melted mozzarella",
    price: "₦10,650",
    category: "Burgers",
  },
  {
    id: 7,
    name: "Jay's Tribute Steak Burger",
    description: "Beef burger with special sauce, served with a side of smiles",
    price: "₦15,640",
    category: "Burgers",
  },
  {
    id: 8,
    name: "Creamy Mashed Potatoes",
    description: "Buttery smooth potatoes perfect for dipping or mixing",
    price: "₦7,000",
    category: "Sides",
  },
  {
    id: 9,
    name: "Roasted Potato Wedges",
    description:
      "Seasoned potato wedges baked until crispy on the outside, fluffy inside",
    price: "₦5,000",
    category: "Sides",
  },
  {
    id: 10,
    name: "Classic French Fries",
    description: "Golden crispy fries, just the way kids love them",
    price: "₦4,500",
    category: "Sides",
  },
  {
    id: 11,
    name: "Dirty Fries",
    description: "Loaded fries with cheese sauce and crispy bacon bits",
    price: "₦5,000",
    category: "Sides",
  },
  {
    id: 12,
    name: "Yam Fries",
    description: "Sweet yam cut into fries and fried to perfection",
    price: "₦5,000",
    category: "Sides",
  },
];

export const loungeMenu = [
  {
    id: 1,
    name: "Grilled crocker fish",
    description: "Grilled crocker fish",
    price: "₦15,000.00",
    category: "Flaming Grills",
  },
  {
    id: 2,
    name: "Grilled cat fish",
    description: "Grilled cat fish",
    price: "₦11,000.00",
    category: "Flaming Grills",
  },
  {
    id: 3,
    name: "Grilled peppered turkey",
    description: "Grilled peppered turkey served with french fries,",
    price: "₦12,000.00",
    category: "Flaming Grills",
  },
  {
    id: 4,
    name: "Bbq chicken laps and chips",
    description: "Grilled chicken laps served with French fries.",
    price: "₦9,600.00",
    category: "Flaming Grills",
  },
  {
    id: 5,
    name: "peppered beef",
    description: "beef steamed up in pepper sauce and well spiced.",
    price: "₦3,500.00",
    category: "Flaming Grills",
  },
  {
    id: 6,
    name: "Peppered beef",
    description: "Peppered beef .",
    price: "₦3,500.00",
    category: "Flaming Grills",
  },
  {
    id: 7,
    name: "Extra chicken",
    description: "chicken laps chucked and served as food of choice.",
    price: "₦6,000.00",
    category: "Flaming Grills",
  },
  {
    id: 8,
    name: "Goat meat pepper soup",
    description: "Goat meat pepper soup",
    price: "₦8,500.00",
    category: "Soups",
  },
  {
    id: 9,
    name: "Catfish pepper soup",
    description: "Catfish pepper soup",
    price: "₦8,500.00",
    category: "Soups",
  },
  {
    id: 10,
    name: "Assorted pepper soup",
    description: "Assorted pepper soup",
    price: "₦9,000.00",
    category: "Soups",
  },
  {
    id: 11,
    name: "French fries",
    description: "French fries",
    price: "₦3,000.00",
    category: "Sides",
  },
  {
    id: 12,
    name: "Sharwama",
    description: "sharwama",
    price: "₦4,500.00",
    category: "Sides",
  },
  {
    id: 13,
    name: "Yam fries",
    description: "Yam fries",
    price: "₦3,700.00",
    category: "Sides",
  },
  {
    id: 14,
    name: "Fried plantain",
    description: "Fried plantain",
    price: "₦3,500.00",
    category: "Sides",
  },
  {
    id: 15,
    name: "Nkwobi",
    description: "Nkwobi",
    price: "₦9,500.00",
    category: "Royal",
  },
  {
    id: 16,
    name: "Peppered snail",
    description: "jumbo snail cooked and sauced.",
    price: "₦5,000.00",
    category: "Royal",
  },
  {
    id: 17,
    name: "Jay's Smokey Jollof",
    description: "Smokey jollof rice served with chunked peppered beef",
    price: "₦9,500.00",
    category: "Special",
  },
  {
    id: 18,
    name: "Infused Steamed Basmati Rice",
    description: "Basmati rice steamed and infused with aromatic and butter",
    price: "₦7,500.00",
    category: "Special",
  },
  {
    id: 19,
    name: "Ofada ricce",
    description: "Ofada rice served with plantain, egg and ofada sauce",
    price: "₦15,000.00",
    category: "Special",
  },
];

