export const foodMenu = [
  {
    id: 1,
    name: "Atlantic Prawn Bisque",
    description:
      "Silken prawn bisque, delicately infused with herbs, served with crisp artisan croutons",
    price: "₦12,666.79",
    category: "Soups",
  },
  {
    id: 2,
    name: "Classic Chicken Pepper Consommé",
    description:
      "Traditional spiced chicken pepper soup, accompanied by freshly baked buns",
    price: "₦15,668",
    category: "Soups",
  },
  {
    id: 3,
    name: "Classic Goat Pepper Pot",
    description: "Slow-simmered goat meat pepper soup with tender yam cubes",
    price: "₦12,093.80",
    category: "Soups",
  },
  {
    id: 4,
    name: "Classic Catfish Pepper Consommé",
    description: "Aromatic catfish pepper soup, served with soft warm buns",
    price: "₦10,559.57",
    category: "Soups",
  },
  {
    id: 5,
    name: "Char-Grilled Chicken Tikka Masala",
    description:
      "Tender chicken in aromatic masala sauce, served with buttered naan bread",
    price: "₦9,740",
    category: "Soups",
  },
  {
    id: 6,
    name: "Smoked Goat Asun & Caramelized Plantain",
    description:
      "Char-grilled goat meat finished with peppers, onions, and ripe plantain",
    price: "₦9,050.20",
    category: "Fingers",
  },
  {
    id: 7,
    name: "Buffalo-Glazed Chicken Wings",
    description:
      "Crispy wings tossed in buffalo glaze, served with roasted garlic aioli",
    price: "₦7,232.40",
    category: "Fingers",
  },
  {
    id: 8,
    name: "Chicken in London",
    description: "Golden-fried chicken bites with a delicate seasoned crust",
    price: "₦6,560.03",
    category: "Fingers",
  },
  {
    id: 9,
    name: "Golden Beer-Battered Onion Rings",
    description: "Served with a honey mustard dipping sauce",
    price: "₦3,445.60",
    category: "Fingers",
  },
  {
    id: 10,
    name: "Classic Atlantic Prawn Cocktail",
    description:
      "Chilled prawns with crisp lettuce and signature cocktail dressing",
    price: "₦13,478.0",
    category: "Fingers",
  },
  {
    id: 11,
    name: "Golden Chicken Taquitos",
    description:
      "Rolled tortillas filled with seasoned chicken, served with a zesty house dip",
    price: "₦3,340.2",
    category: "Fingers",
  },
  {
    id: 12,
    name: "Sticky Glazed Lamb Ribs",
    description: "Slow-roasted lamb ribs finished in a rich, glossy glaze",
    price: "₦10,735",
    category: "Fingers",
  },
  {
    id: 13,
    name: "Shrimps in Mayo Spring Rolls",
    description: "Golden pastries filled with savory Shrimps and mayo sauce",
    price: "₦2,730",
    category: "Spring Roll",
  },
  {
    id: 14,
    name: "Chicken spring roll",
    description: "Golden pastries filled with Spiced chicken",
    price: "₦2,250",
    category: "Spring Roll",
  },
  {
    id: 15,
    name: "Vegetarian spring roll",
    description: "Golden pastries filled with savory vegetables and spices ",
    price: "₦2,000",
    category: "Spring Roll",
  },
  {
    id: 16,
    name: "Beef spring roll",
    description: "Golden pastries filled with umami flavored beef",
    price: "₦2,250",
    category: "Spring Roll",
  },
];

export const desertMenu = [
  {
    id: 1,
    name: "Braise de Jarret d’Agneau",
    description: "Slow-braised lamb shank served with velvety mashed potatoes",
    price: "₦35,668",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 2,
    name: "Jay’s Golden Hammer",
    description:
      "Signature Thor’s Hammer cut, expertly roasted and served with herb potato wedges",
    price: "₦70,689",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 3,
    name: "Teriyaki-Glazed Ribeye Steak",
    description: "Char-grilled ribeye served with vibrant chimichurri sauce",
    price: "₦28,875",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 4,
    name: "Ribeye Steak with Fresh Chimichurri",
    description: "Char-grilled ribeye served with vibrant chimichurri sauce",
    price: "₦28,875",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 5,
    name: "Bone-In Prime Steak",
    description: "Finished with a luxurious red wine jus",
    price: "₦32,200",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 6,
    name: "Cowboy Tomahawk Steak",
    description: "An impressive long-bone steak, flame-grilled to perfection",
    price: "₦38,625",
    category: "Steaks & Premium Cuts",
  },
  {
    id: 7,
    name: "Linguine alla Bolognese Classico",
    description: "Traditional slow-cooked meat ragu with fine herbs",
    price: "₦23,547",
    category: "Pasta Selection",
  },
  {
    id: 8,
    name: "Penne all’Arrabbiata",
    description: "Al dente penne in a bold tomato and chili sauce",
    price: "₦17,679.90",
    category: "Pasta Selection",
  },
  {
    id: 9,
    name: "Fettuccine Alfredo with Grilled Chicken",
    description: "Creamy parmesan sauce finished with tender chicken",
    price: "₦24,962",
    category: "Pasta Selection",
  },
  {
    id: 10,
    name: "Four-Cheese Maccheroni Indulgence",
    description:
      "A rich, creamy, baked macaroni and cheese dish featuring a blend of four distinct cheeses to create layers of flavor and a luxurious texture",
    price: "₦18,983.90",
    category: "Pasta Selection",
  },
  {
    id: 11,
    name: "Wok-Tossed Teriyaki Chicken Noodles",
    description: "Silky noodles with glazed chicken and vegetables",
    price: "₦15,667.79",
    category: "Asian Inspiration",
  },
  {
    id: 12,
    name: "Traditional Shoyu Ramen",
    description: "Classic Japanese noodle soup with soy-based broth",
    price: "₦13,652",
    category: "Asian Inspiration",
  },
  {
    id: 13,
    name: "Coconut-Infused Seafood Rice",
    description:
      "Fragrant rice delicately cooked with seafood and coconut essence",
    price: "₦23,683",
    category: "Rice and Signature Specialties",
  },
  {
    id: 14,
    name: "Mediterranean Greek Seafood Rice",
    description: "Rice infused with herbs, olive oil, and fresh seafood",
    price: "₦24,287.50",
    category: "Rice and Signature Specialties",
  },
  {
    id: 15,
    name: "Surf & Turf Prawn & Chicken Rice",
    description: "A refined combination of succulent prawns and tender chicken",
    price: "₦19,887.50",
    category: "Rice and Signature Specialties",
  },
  {
    id: 16,
    name: "Sizzling Beef Stir-Fry",
    description: "Premium beef strips wok-seared with seasonal vegetables",
    price: "₦15,657",
    category: "Rice and Signature Specialties",
  },
  {
    id: 17,
    name: "Golden Pineapple Fried Rice",
    description: "Aromatic rice tossed with pineapple and spices",
    price: "₦13,362.50",
    category: "Rice and Signature Specialties",
  },
  {
    id: 18,
    name: "Offada Reloaded – Chef’s Interpretation",
    description:
      "Traditional Nigerian Ofada rice elevated with rich accompaniments",
    price: "₦18,992.80",
    category: "Rice and Signature Specialties",
  },
  {
    id: 19,
    name: "Jay’s Signature Basmati Rice",
    description:
      "Perfectly steamed flavored and spiced long-grain basmati rice infused with Gizzard and glazed plantain.",
    price: "₦14,998.90",
    category: "Rice and Signature Specialties",
  },
  {
    id: 20,
    name: "The Grand Seafood Boil (serves 2)",
    description: "A luxurious assortment of seafood, infused with house spices",
    price: "₦57,667",
    category: "Seafood Delicacies",
  },
  {
    id: 21,
    name: "Blood Orange–Glazed Atlantic Salmon",
    description: "Pan-seared salmon finished with citrus reduction",
    price: "₦20,674",
    category: "Seafood Delicacies",
  },
  {
    id: 22,
    name: "Creamy Lemon & Dill Salmon",
    description: "Salmon in a delicate cream sauce infused with fresh dill",
    price: "₦22,235",
    category: "Seafood Delicacies",
  },
  {
    id: 23,
    name: "“Marry Me” Signature Salmon",
    description: "Chef’s celebrated salmon in a rich, velvety sauce",
    price: "₦24,186",
    category: "Seafood Delicacies",
  },
  {
    id: 24,
    name: "Cajun-Spiced Tiger Prawns",
    description: "Succulent prawns finished with bold Cajun seasoning",
    price: "₦22,359.37",
    category: "Seafood Delicacies",
  },
  {
    id: 25,
    name: "Cajun-Spiced Tiger Prawns",
    description: "Succulent prawns finished with bold Cajun seasoning",
    price: "₦22,359.37",
    category: "Seafood Delicacies",
  },
  {
    id: 26,
    name: "Ocean’s Harvest Platter",
    description: "An exquisite selection of premium seafood",
    price: "₦38,270",
    category: "Seafood Delicacies",
  },
  {
    id: 27,
    name: "Flames of the Sea",
    description: "Chef’s flambéed seafood showcase",
    price: "₦47,359",
    category: "Seafood Delicacies",
  },
  {
    id: 28,
    name: "Classic Caesar Salad",
    description: "Crisp romaine, parmesan shavings, and house dressing",
    price: "₦15,750",
    category: "Salads",
  },
  {
    id: 29,
    name: "Chilled Shrimp Garden Salad",
    description: "Fresh greens topped with tender shrimp",
    price: "₦12,650",
    category: "Salads",
  },
  {
    id: 30,
    name: "Creamy Classic Coleslaw",
    description: "Finely shredded cabbage in a delicate dressing",
    price: "₦9,137.50",
    category: "Salads",
  },
  {
    id: 31,
    name: "Mediterranean Pasta Salad",
    description: "Pasta tossed with herbs, vegetables, and olive oil",
    price: "₦10,276.05",
    category: "Salads",
  },
  {
    id: 32,
    name: "Golden Orchard Fruit Tart",
    description: "Seasonal fruits on a buttery pastry base",
    price: "₦9,670",
    category: "Dessert",
  },
  {
    id: 33,
    name: "Vanilla double Panna Cotta",
    description: "Silky Italian dessert with subtle vanilla notes",
    price: "₦9,060",
    category: "Dessert",
  },
  {
    id: 34,
    name: "Decadent Chocolate Indulgence Cake",
    description: "Rich chocolate layers with smooth ganache",
    price: "₦10,137",
    category: "Dessert",
  },
  {
    id: 35,
    name: "Classic Cinnamon-Spiced Apple Pie",
    description: "Warm apple filling encased in golden past",
    price: "₦12,367",
    category: "Dessert",
  },
];

export const kidsMenu = [
  {
    id: 1,
    name: "Chicken & Chips",
    description:
      "Crispy chicken tenders with golden French fries, served with ketchup",
    price: "₦7,000",
    category: "Main Dishes",
  },
  {
    id: 2,
    name: "Cheesy Mac & Cheese",
    description: "Creamy elbow pasta baked with three kinds of melty cheese",
    price: "₦9,000",
    category: "Main Dishes",
  },
  {
    id: 3,
    name: "Sticky Chicken Wings",
    description: "Sweet and tangy glazed wings that are finger-licking good",
    price: "₦8,950",
    category: "Main Dishes",
  },
  {
    id: 4,
    name: "Jollof Rice & Grilled Chicken",
    description: "Flavorful tomato rice with tender grilled chicken drumstick",
    price: "₦10,500",
    category: "Main Dishes",
  },
  {
    id: 5,
    name: "Chicken Buffalo Burger",
    description:
      "Juicy chicken patty with mild buffalo sauce and crispy lettuce",
    price: "₦12,790",
    category: "Burgers",
  },
  {
    id: 6,
    name: "Chicken Parmesan Burger",
    description:
      "Breaded chicken patty topped with marinara sauce and melted mozzarella",
    price: "₦10,650",
    category: "Burgers",
  },
  {
    id: 7,
    name: "Jay's Tribute Steak Burger",
    description: "Beef burger with special sauce, served with a side of smiles",
    price: "₦15,640",
    category: "Burgers",
  },
  {
    id: 8,
    name: "Creamy Mashed Potatoes",
    description: "Buttery smooth potatoes perfect for dipping or mixing",
    price: "₦7,000",
    category: "Sides",
  },
  {
    id: 9,
    name: "Roasted Potato Wedges",
    description:
      "Seasoned potato wedges baked until crispy on the outside, fluffy inside",
    price: "₦5,000",
    category: "Sides",
  },
  {
    id: 10,
    name: "Classic French Fries",
    description: "Golden crispy fries, just the way kids love them",
    price: "₦4,500",
    category: "Sides",
  },
  {
    id: 11,
    name: "Dirty Fries",
    description: "Loaded fries with cheese sauce and crispy bacon bits",
    price: "₦5,000",
    category: "Sides",
  },
  {
    id: 12,
    name: "Yam Fries",
    description: "Sweet yam cut into fries and fried to perfection",
    price: "₦5,000",
    category: "Sides",
  },
];

export const loungeMenu = [
  {
    id: 1,
    name: "Grilled crocker fish",
    description: "Grilled crocker fish",
    price: "₦15,000.00",
    category: "Flaming Grills",
  },
  {
    id: 2,
    name: "Grilled cat fish",
    description: "Grilled cat fish",
    price: "₦11,000.00",
    category: "Flaming Grills",
  },
  {
    id: 3,
    name: "Grilled peppered turkey",
    description: "Grilled peppered turkey served with french fries,",
    price: "₦12,000.00",
    category: "Flaming Grills",
  },
  {
    id: 4,
    name: "Bbq chicken laps and chips",
    description: "Grilled chicken laps served with French fries.",
    price: "₦9,600.00",
    category: "Flaming Grills",
  },
  {
    id: 5,
    name: "peppered beef",
    description: "beef steamed up in pepper sauce and well spiced.",
    price: "₦3,500.00",
    category: "Flaming Grills",
  },
  {
    id: 6,
    name: "Peppered beef",
    description: "Peppered beef .",
    price: "₦3,500.00",
    category: "Flaming Grills",
  },
  {
    id: 7,
    name: "Extra chicken",
    description: "chicken laps chucked and served as food of choice.",
    price: "₦6,000.00",
    category: "Flaming Grills",
  },
  {
    id: 8,
    name: "Goat meat pepper soup",
    description: "Goat meat pepper soup",
    price: "₦8,500.00",
    category: "Soups",
  },
  {
    id: 9,
    name: "Catfish pepper soup",
    description: "Catfish pepper soup",
    price: "₦8,500.00",
    category: "Soups",
  },
  {
    id: 10,
    name: "Assorted pepper soup",
    description: "Assorted pepper soup",
    price: "₦9,000.00",
    category: "Soups",
  },
  {
    id: 11,
    name: "French fries",
    description: "French fries",
    price: "₦3,000.00",
    category: "Sides",
  },
  {
    id: 12,
    name: "Sharwama",
    description: "sharwama",
    price: "₦4,500.00",
    category: "Sides",
  },
  {
    id: 13,
    name: "Yam fries",
    description: "Yam fries",
    price: "₦3,700.00",
    category: "Sides",
  },
  {
    id: 14,
    name: "Fried plantain",
    description: "Fried plantain",
    price: "₦3,500.00",
    category: "Sides",
  },
  {
    id: 15,
    name: "Nkwobi",
    description: "Nkwobi",
    price: "₦9,500.00",
    category: "Royal",
  },
  {
    id: 16,
    name: "Peppered snail",
    description: "jumbo snail cooked and sauced.",
    price: "₦5,000.00",
    category: "Royal",
  },
  {
    id: 17,
    name: "Jay's Smokey Jollof",
    description: "Smokey jollof rice served with chunked peppered beef",
    price: "₦9,500.00",
    category: "Special",
  },
  {
    id: 18,
    name: "Infused Steamed Basmati Rice",
    description: "Basmati rice steamed and infused with aromatic and butter",
    price: "₦7,500.00",
    category: "Special",
  },
  {
    id: 19,
    name: "Ofada ricce",
    description: "Ofada rice served with plantain, egg and ofada sauce",
    price: "₦15,000.00",
    category: "Special",
  },
];

export const loungeDrinksMenu = [
  {
    id: 1,
    name: "Martell VS",
    price: "₦90000.00",
    category: "Brandy",
  },
  {
    id: 2,
    name: "Martell Blue Swift",
    price: "₦190000.00",
    category: "Brandy",
  },
  {
    id: 3,
    name: "Martell XO",
    price: "₦700000.00",
    category: "Brandy",
  },
  {
    id: 4,
    name: "Hennessy VS",
    price: "₦105000.00",
    category: "Brandy",
  },
  {
    id: 5,
    name: "Hennessy XO",
    price: "₦750000.00",
    category: "Brandy",
  },
  {
    id: 6,
    name: "Hennessy VSOP",
    price: "₦190000.00",
    category: "Brandy",
  },
  {
    id: 7,
    name: "Jameson Black Barrel",
    price: "₦75000.00",
    category: "Whiskey",
  },
  {
    id: 8,
    name: "Jagermeiser",
    price: "₦40000.00",
    category: "Rum",
  },
  {
    id: 9,
    name: "Belaire Rose",
    price: "₦120000.00",
    category: "Rose",
  },
  {
    id: 10,
    name: "Belaire Luxe",
    price: "₦120000.00",
    category: "Champagne",
  },
  {
    id: 11,
    name: "Moet & Chandon Rose",
    price: "₦210000.00",
    category: "Rose/Champagne",
  },
  {
    id: 12,
    name: "Moet&Chandon Brut",
    price: "₦180000.00",
    category: "Brut/Champagne",
  },
  {
    id: 13,
    name: "Jack Daniels",
    price: "₦60000.00",
    category: "Old No. 7",
  },
  {
    id: 14,
    name: "Bacardi White",
    price: "₦35000.00",
    category: "Rum",
  },
  {
    id: 15,
    name: "Bacardi Gold",
    price: "₦35000.00",
    category: "Rum",
  },
  {
    id: 16,
    name: "Captain Morgan",
    price: "₦25000.00",
    category: "Rum",
  },
  {
    id: 17,
    name: "Gordon's Gin",
    price: "₦20000.00",
    category: "Gin",
  },
  {
    id: 18,
    name: "Malibu",
    price: "₦28000.00",
    category: "Rum",
  },
  {
    id: 19,
    name: "Baileys",
    price: "₦40000.00",
    category: "Irish Cream",
  },
  {
    id: 20,
    name: "Kahlua Cafe",
    price: "₦30000.00",
    category: "Coffee-flavored cafe Liqueur",
  },
  {
    id: 21,
    name: "Camino Gold",
    price: "₦35000.00",
    category: "Tequila",
  },
  {
    id: 22,
    name: "Camino Silver",
    price: "₦35000.00",
    category: "Tequila",
  },
  {
    id: 23,
    name: "Sierra Silver",
    price: "₦40000.00",
    category: "Tequila",
  },
  {
    id: 24,
    name: "Sierra Gold",
    price: "₦40000.00",
    category: "Tequila",
  },
  {
    id: 25,
    name: "Four Cousins",
    price: "₦23000.00",
    category: "Wine",
  },
  {
    id: 26,
    name: "Carlo Rossi",
    price: "₦30000.00",
    category: "Wine",
  },
  {
    id: 27,
    name: "Patron Silver",
    price: "₦50000.00",
    category: "Tequila",
  },
  {
    id: 28,
    name: "Olmeca Blanco",
    price: "₦50000.00",
    category: "Tequila",
  },
  {
    id: 29,
    name: "Macallan 15 Years",
    price: "₦290000.00",
    category: "Whiskey",
  },
  {
    id: 30,
    name: "Macallan 18 Years",
    price: "₦290000.00",
    category: "Whiskey",
  },
  {
    id: 31,
    name: "Macallan 12 Years",
    price: "₦95000.00",
    category: "Whiskey",
  },
  {
    id: 32,
    name: "Glenfiddich 15 Years",
    price: "₦170000.00",
    category: "Whiskey",
  },
  {
    id: 33,
    name: "Glenfiddich 12 Years",
    price: "₦100000.00",
    category: "Whiskey",
  },
  {
    id: 34,
    name: "Johnnie Walker Black Label",
    price: "₦75000.00",
    category: "Whiskey",
  },
  {
    id: 35,
    name: "Johnnie Walker Green Label",
    price: "₦115000.00",
    category: "Whiskey",
  },
  {
    id: 36,
    name: "Singleton 12 Years",
    price: "₦100000.00",
    category: "Whiskey",
  },
  {
    id: 37,
    name: "Singleton 15 Years",
    price: "₦170000.00",
    category: "Whiskey",
  },
  {
    id: 38,
    name: "Power Horse",
    price: "₦3500.00",
    category: "Energy Drink",
  },
  {
    id: 39,
    name: "Red Bull",
    price: "₦3500.00",
    category: "Energy Drink",
  },
  {
    id: 40,
    name: "Cranberry Juice",
    price: "₦8000.00",
    category: "Juice",
  },
  {
    id: 41,
    name: "Apple Juice",
    price: "₦6000.00",
    category: "Juice",
  },
  {
    id: 42,
    name: "Pineapple Juice",
    price: "₦6000.00",
    category: "Juice",
  },
  {
    id: 43,
    name: "Coke",
    price: "₦1000.00",
    category: "coke",
  },
  {
    id: 44,
    name: "Sprite",
    price: "₦1000.00",
    category: "sprite",
  },
  {
    id: 45,
    name: "Bottle Water",
    price: "₦1000.00",
    category: "water",
  },
  {
    id: 46,
    name: "Heineken",
    price: "₦2500.00",
    category: "Beer",
  },
  {
    id: 47,
    name: "Guinness Big Stout",
    price: "₦2500.00",
    category: "Stout",
  },
  {
    id: 48,
    name: "Guinness Small Stout",
    price: "₦2000.00",
    category: "Stout",
  },
  {
    id: 49,
    name: "Shot of Bacardi",
    price: "₦2500.00",
    category: "Shot",
  },
  {
    id: 50,
    name: "Shot of Tequila",
    price: "₦2500.00",
    category: "tequila",
  },
  {
    id: 51,
    name: "Martell XO Davido Limited Edition",
    price: "₦800000.00",
    category: "Davido Limited Edition",
  },
  {
    id: 52,
    name: "Sweet Kiss",
    price: "₦23000.00",
    category: "Wine",
  },
  {
    id: 53,
    name: "Robertson Winery",
    price: "₦25000.00",
    category: "Wine",
  },
  {
    id: 54,
    name: "Agor Wine",
    price: "₦25000.00",
    category: "Wine",
  },
  {
    id: 55,
    name: "Veuve Clicquot Rich",
    price: "₦300000.00",
    category: "Champagne",
  },
  {
    id: 56,
    name: "G.H. Mumm",
    price: "₦85000.00",
    category: "Champagne",
  },
  {
    id: 57,
    name: "Clase Azul Plata",
    price: "₦350000.00",
    category: "tequila",
  },
  {
    id: 58,
    name: "Casamigos Reposado",
    price: "₦300000.00",
    category: "tequila",
  },
  {
    id: 59,
    name: "Casamigos Blanco",
    price: "₦250000.00",
    category: "tequila",
  },
  {
    id: 60,
    name: "Absolut",
    price: "₦50000.00",
    category: "vodka",
  },
  {
    id: 61,
    name: "Ciroc Blue",
    price: "₦70000.00",
    category: "Vodka",
  },
  {
    id: 62,
    name: "Grey Goose",
    price: "₦75000.00",
    category: "vodka",
  },
  {
    id: 63,
    name: "Bombay Sapphire",
    price: "₦35000.00",
    category: "Gin",
  },
  {
    id: 64,
    name: "Beefeater",
    price: "₦30000.00",
    category: "Gin",
  },
  {
    id: 65,
    name: "Glenfiddich 18 Years",
    price: "₦250000.00",
    category: "whiskey",
  },
  {
    id: 66,
    name: "Glenfiddich 21 Years",
    price: "₦390000.00",
    category: "whiskey",
  },
  {
    id: 67,
    name: "Jameson Green",
    price: "₦45000.00",
    category: "whiskey",
  },
  {
    id: 68,
    name: "BLUE NUN 24K GOLD (CHAMPAGNE)",
    price: "₦520000.00",
    category: "Champagne",
  },
  {
    id: 69,
    name: "Cabernet Sauvignon (BLUE NUN)",
    price: "₦20000.00",
    category: "Wine",
  },
  {
    id: 70,
    name: "Pink Ice (BLUE NUN)",
    price: "₦20000.00",
    category: "Wine",
  },
  {
    id: 71,
    name: "Smirnoff Ice Double Black",
    price: "₦2500.00",
    category: "Beer",
  },
  {
    id: 72,
    name: "Desperado",
    price: "₦2500.00",
    category: "Beer",
  },
  {
    id: 73,
    name: "Takeaway",
    price: "₦1000.00",
    category: "Supplies",
  },
  {
    id: 74,
    name: "Hollandia Yoghurt",
    price: "₦1500.00",
    category: "Yoghurt",
  },
  {
    id: 75,
    name: "Budweiser",
    price: "₦2500.00",
    category: "Beer",
  },
  {
    id: 76,
    name: "Star Radler",
    price: "₦2500.00",
    category: "Beer",
  },
  {
    id: 77,
    name: "Monster",
    price: "₦3500.00",
    category: "Energy Drink",
  },
  {
    id: 78,
    name: "Ballentine",
    price: "₦40000.00",
    category: "Whiskey",
  },
  {
    id: 79,
    name: "Broken Glass",
    price: "₦5000.00",
    category: "Supplies",
  },
  {
    id: 80,
    name: "Escudo Rojo",
    price: "₦20000.00",
    category: "Wine",
  },
  {
    id: 81,
    name: "Chamdor",
    price: "₦12000.00",
    category: "Wine",
  },
  {
    id: 82,
    name: "Patron Reposado",
    price: "₦50000.00",
    category: "Tequila",
  },
  {
    id: 83,
    name: "Angel Red Grape",
    price: "₦15000.00",
    category: "Juice",
  },
  {
    id: 84,
    name: "Juice",
    price: "₦8000.00",
    category: "Juice",
  },
];